name: CI/CD
on:
  push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.x'
          channel: 'stable'
      - run: flutter pub get
      - id: pages
        uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.PAGES_TOKEN }}
      - run: flutter build web --base-href="${{ steps.pages.outputs.base_url }}/"
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/web
          if-no-files-found: error
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v3
