name: CI/CD
on:
  push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.x'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
      - name: Install Flutter packages
        run: flutter pub get
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.PAGES_TOKEN }}
      - name: Build the Web app
        run: flutter build web --base-href="${{ steps.pages.outputs.base_path }}/" --dart-define=OWM_API_KEY=${{ secrets.OWM_API_KEY }}
      - name: Upload the Web app
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/web
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy the Web app
        id: deployment
        uses: actions/deploy-pages@v3
