name: CI/CD
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci_cd.yml'
      - 'pubspec.yaml'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the full history. Needed for the correct calculation of the last update date.
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
      - name: Install Flutter packages
        run: flutter pub get
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.PAGES_TOKEN }}
      - name: Project build cache
        uses: actions/cache@v3
        with:
          path: |
            build/
            .dart_tool/
          key: ${{ runner.os }}-interactive-cv_build
      - name: Build the Web app
        run: |
          export LAST_UPDATE=`git ls-tree -r --name-only HEAD lib/ images/ web/ | while read filename; do echo "$(git log -1 --format=%ad --date=iso -- $filename) $filename"; done | sort -r | head -n 1 | cut -d' ' -f1`
          flutter build web --base-href="${{ steps.pages.outputs.base_path }}/" \
            --dart-define=OWM_API_KEY=${{ secrets.OWM_API_KEY }} --dart-define=LAST_UPDATE=$LAST_UPDATE \
            --dart-define=GITHUB_PROFILE_TOKEN=${{ secrets.GH_PROFILE_TOKEN }} \
            --dart-define=STACKEXCHANGE_ACCESS_TOKEN="${{ secrets.STACKEXCHANGE_ACCESS_TOKEN }}" \
            --dart-define=STACKEXCHANGE_KEY="${{ secrets.STACKEXCHANGE_KEY }}"
      - name: Upload the Web app
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/web
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy the Web app
        id: deployment
        uses: actions/deploy-pages@v3
