name: Scrapers
on:
  schedule:
    - cron: '15 9 * * *'
  workflow_dispatch:
env:
  GITHUB_PROFILE_TOKEN: ${{ secrets.GH_PROFILE_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MOZ_HEADLESS: 1
  LINKEDIN_COOKIES: ${{ secrets.LINKEDIN_COOKIES }}
jobs:
  Scrapers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 'latest'
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'
          cache: 'pip'
      - name: Checking cache of WebDriverManager
        uses: actions/cache@v4
        with:
          path: ~/.wdm
          key: ${{ runner.os }}-wdm-drivers
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the script
        run: python scrapers.py
