name: Scrapers
on:
  schedule:
    - cron: '15 9 * * *'
  workflow_dispatch:
    inputs:
      scrapers:
        description: 'Choose the scraper to run'
        default: 'all'
        options:
          - 'linkedin'
          - 'hsoub_academy'
env:
  GITHUB_PROFILE_TOKEN: ${{ secrets.GH_PROFILE_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MOZ_HEADLESS: 1
  LINKEDIN_COOKIES: ${{ secrets.LINKEDIN_COOKIES }}
  LINKEDIN_PROFILE_URL: ${{ vars.LINKEDIN_PROFILE_URL }}
  HSOUB_ACADEMY_PROFILE_URL: ${{ vars.HSOUB_ACADEMY_PROFILE_URL }}
jobs:
  Scrapers:
    runs-on: ubuntu-latest
    steps:
      - name: Install Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 'latest'
      - name: Checking cache of WebDriverManager
        uses: actions/cache@v4
        with:
          path: ~/.wdm
          key: ${{ runner.os }}-wdm-drivers
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scrap Hsoub Academy profile
        run: python scrapers.py hsoub_academy
        if: ${{ github.event.inputs.scrapers == 'hsoub_academy' || github.event.inputs.scrapers == 'all' || github.event_name == 'schedule' }}
      - name: Scrap Mostaql reviews
        run: python scrapers.py mostaql_reviews
        if: ${{ github.event.inputs.scrapers == 'mostaql_reviews' || github.event.inputs.scrapers == 'all' || github.event_name == 'schedule' }}
      - name: Scrap LinkedIn profile
        run: python scrapers.py linkedin
        if: ${{ github.event.inputs.scrapers == 'linkedin' || github.event.inputs.scrapers == 'all' || github.event_name == 'schedule' }}
